# Generated by Django 5.0.6 on 2024-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tana_software_solution', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('lastname_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=50)),
                ('joined_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
