# Generated by Django 5.0.6 on 2024-05-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tana_software_solution', '0004_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lastname_name',
            new_name='last_name',
        ),
    ]
