# Generated by Django 5.0.6 on 2024-06-04 11:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tana_software_solution', '0005_rename_lastname_name_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
