# Generated by Django 5.0.4 on 2024-05-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(max_length=200)),
                ('rating_count', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')])),
                ('username', models.TextField()),
                ('user_job_title', models.CharField(max_length=200)),
                ('review', models.TextField()),
            ],
        ),
    ]
