# Generated by Django 5.0.4 on 2024-05-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_frequentlyaskedquestion_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='TestimonialReview',
        ),
    ]
